### PR TITLE
Add basic pre-commit testing, upgrade pre-commit

### PR DESCRIPTION
**Pull request by michaelaw320**
Add basic pre-commit testing that covers `terraform_fmt` `terraform_docs`

### CODE REVIEW

**Review by hanscg — COMMENTED** [review]
Maybe better to use pre-commit/actions?

**Review by hanscg — COMMENTED** [review]
From the checks: `ERROR: terraform-docs is required by terraform_docs pre-commit hook but is not installed or in the system's PATH.`

I think terraform-docs has to be installed first

**Comment by michaelaw320** [comment]
Todo: update to make it similar with upstream https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/.github/workflows/pre-commit.yml

**Review by hanscg — APPROVED** [review]
LGTM

**Pull request merged**
